# Generated by Django 6.0.7 on 2026-08-01 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('pharmacy', '0002_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='fulfilment_status',
            field=models.CharField(choices=[('PENDING', 'Awaiting preparation'), ('READY', 'Ready for collection'), ('COLLECTED', 'Collected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='pharmacy.pharmacy'),
        ),
    ]
