# Generated by Django 6.0.7 on 2026-08-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='activation_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
